name: stochpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  # Required dependencies
  - gmt=6.4.0
  - numpy>=1.22
  - pandas
  - xarray
  - netCDF4
  - packaging
  - pygmt
  - clawpack
  - basemap
  - basemap-data-hires
  - matplotlib
  - scikit-learn
  - rockhound
  - tqdm
  - pip
  - cartopy
  - geopy
  - pip:
    - clawpack
  # Development dependencies (general)
  - build
  - dvc
  - jupyter
  - make
  - pip